### ISSUE TITLE
content formatting bug

### ISSUE THREAD

**Issue by sveesible** [googlecodelabs/cloud-lamp-migration#1]
Under the sub-topic : Create a different schema to hybrid version

The command should be one solid block command, but it is broken into 3 sections, a black box around the first line, then white space and the database name "gcpnext16hybrid" and then another black code box with the "< export.sql;"
so it looks much like this example:
`$ mysql -u "root" -h "localhost" -p`
gcpnext16hybrid
`< export.sql;`

When it should be all a single command like this

`$ mysql -u "root" -h "localhost" -p  gcpnext16hybrid < export.sql;`

**Comment by hostirosti** [comment]
Hi Brad,

thank you for the pointer. It is fixed now.

Cheers,
Robert
